# CI/CD pipeline for SONIC PoC
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
pr: none
  
pool:
  name: ERGATIS

stages:
  - stage: Build
    displayName: 'Build Image'
    jobs:
      - job: Build
        displayName: 'Dummy Build'
        steps:
          - script: |
              echo Notify Discord
              chmod +x scripts/notify_discord.sh
              ./scripts/notify_discord.sh $(DISCORD_WEBHOOK_URL) "SONIC POC Build ID: $(Build.BuildId)"
            displayName: 'Notify Discord'
            condition: succeeded()
            env:
              DISCORD_WEBHOOK_URL: $(DISCORD_WEBHOOK_URL)