# CI/CD pipeline for Sonic PoC

trigger:
  - master
  
pool:
  name: ERGATIS

stages:
  - stage: Analyze
    displayName: 'Analyze Code Quality'
    jobs:
      - job: SonarCloudAnalysis
        displayName: 'Analyze Code with SonarCloud'
        steps:
          - script: |
              echo TODO: Add SonarCloud Analysis
  
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        displayName: 'Build Docker Image'
        steps:
          - script: |
              echo Build Docker Image
              make build
          - script: |
              echo Push Docker Image
              make push

  - stage: UnitTests
    displayName: 'UnitTests'
    jobs:
      - job: UnitTests
        displayName: 'Run Unit Tests'
        steps:
          - script: |
              echo TODO: Add Unit Tests

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    jobs:
      - job: Deploy
        displayName: 'Deploy Docker Image to Azure Web App'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureRM-SONIC'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp config container set --name SONIC --resource-group SONIC --docker-custom-image-name thefueley/sonic-poc:$(Build.BuildId)
                az webapp config appsettings set --name SONIC --resource-group SONIC --settings WEBSITES_PORT=5000