# Build the Sonic image
FROM python:3.12.6-alpine3.20 AS build-sonic
ARG BUILD_REF
ARG BUILD_DATE
ARG APP_VERSION

WORKDIR /sonic
COPY . /sonic

COPY  requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apk add --no-cache shadow && \
    groupadd -g 1000 sonic && \
    useradd -u 1000 -d /sonic -g sonic -s /bin/sh -m sonic && \
    chown -R sonic:sonic /sonic

USER sonic

# Set environment variables
ENV FLASK_APP=sonic
ENV APP_VERSION=${APP_VERSION}

CMD ["sh", "-c", "flask init-db && waitress-serve --ident=OlympiLearn --port=5000 --call 'sonic:create_app'"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sonic-poc" \
      org.opencontainers.image.authors="thefueley <5083152+thefueley@users.noreply.github.com>" \
      org.opencontainers.image.source="https://github.com/thefueley/sonic-poc" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="SONIC" \