"""add email with unique constraint

Revision ID: 07855cc3caec
Revises: 940b691203e9
Create Date: 2024-11-13 08:10:13.126528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07855cc3caec'
down_revision = '940b691203e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
